services:
  mongo:
    image: mongo:8.0-noble
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:8-alpine3.21
    restart: always
    ports:
      - '6379:6379'

volumes:
  mongo-data:
    driver: local
